// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhwriprgbectkxifvylb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5od3JpcHJnYmVjdGt4aWZ2eWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MjY5MjEsImV4cCI6MjA1MDUwMjkyMX0.zQw2BjgvoLw4u8YZ7DNAhG5YQ3r2XaX_8jhODNeIKgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);