// This file is automatically generated. Do not edit it directly.
import { Database } from '@/types/database.types';

// Import the supabase client like this:
// import { supabase } from "../integrations/supabase/client";

export const supabase = createClient<Database>(
  import.meta.env.VITE_SUPABASE_URL!,
  import.meta.env.VITE_SUPABASE_ANON_KEY!
);

function createClient<T>(arg0: any, arg1: any) {
  throw new Error('Function not implemented.');
}
