name: Initialize Environments

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  init-environments:
    runs-on: ubuntu-latest
    steps:
      - name: Create Preview Environment
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/environments/preview \
            -f wait_timer=0 \
            -f deployment_branch_policy=null

      - name: Create Production Environment
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/environments/production \
            -f wait_timer=30 \
            -f deployment_branch_policy='{"protected_branches":true,"custom_branch_policies":false}'